# -*- coding: utf-8 -*-
"""iterator generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6wmKqDM4gcfbv8n64LKBqDHzf0C7V2O
"""

l = [1,2,3,4,5]

next(l)

l = iter(l)

next(l)

next(l)

next(l)

next(l)

next(l)

next(l)

a = 56

next(a)

a = iter(a)

t = (5,6,7,8,8)

next(t)

t = iter(t)

next(t)

next(t)

next(t)

r = range(6)

next(r)

r = iter(r)

next(r)

list(range(0,45,3))

def gencube(n) :
    l = []
    for i in range(n) : 
        l.append(i**3)
    return l

gencube(6000000)

for i in range(10000000000000000):
    print(i)

def gencube(n) :
    
    for i in range(n) : 
        yield i**3

gencube(10)

for i in gencube(90):
    print(i)

def fib(n):
    a = 1
    b = 1
    for i in range(n):
        yield a,i
        a,b = b , a+b

for i in fib(10000):
    print(i)

def fib1(n) : 
    a = 1
    b = 1
    output = []
    for i in range(n) : 
        output.append(a)
        a,b = b , a+b
    return output

fib1(10)

def fib(n):
    a = 0; 
    b = 1;
    for i in range(n):
        print(type(print(a)))
        a, b = b , a + b;

fib(10)

print("something in console")

f = open("test1.txt","w")

# Commented out IPython magic to ensure Python compatibility.
# %ls

pwd()

f = open('test1.txt' , "w")

f.write("this is dsfsaf adfdsaf safdsa dsafsadfdsa dsaf sfdsf safsa sadf safdsaf sfdsaf safsaf sadfsa dsaf afs dsaf sadfdsa sadf asdfd sadsaf asdfd safd asf asf sdfd ssadfsadf saf sadfmy first file operation to someting in my test2.txt")

f.close()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test2.txt
# this is a data i would like to store in my file

# Commented out IPython magic to ensure Python compatibility.
# %ls

f = open('test1.txt')

f.read()

f.write("fdsafdsafsadf f dsaf asfda sdf dafsa df")

f.read()

f.read()

f.seek(5)

f.read()

f.read()

f.seek(0)

f.read()

f.tell()

f.seek(5)

f.tell(
)

f.close()

f = open("test1.txt" , "r+")

f.read()

f.readline()

f.tell()

f.seek(0)

f.readline()

f.readline()

f = open('google.txt' , "w")

f.write("""Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five companies in the American information technology industry, along with Amazon, Apple, Meta (Facebook) and Microsoft.[10]

Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University in California. Together they own about 14% of its publicly-listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly-owned subsidiary of Alphabet Inc.. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's Internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.[11]

In 2021, the Alphabet Workers Union was founded, mainly composed of Google employees.[12]

The company's rapid growth since incorporation has included products, acquisitions, and partnerships beyond Google's core search engine, (Google Search). It offers services designed for work and productivity (Google Docs, Google Sheets, and Google Slides), email (Gmail), scheduling and time management (Google Calendar), cloud storage (Google Drive), instant messaging and video chat (Google Duo, Google Chat, and Google Meet), language translation (Google Translate), mapping and navigation (Google Maps, Waze, Google Earth, and Street View), podcast hosting (Google Podcasts), video sharing (YouTube), blog publishing (Blogger), note-taking (Google Keep and Jamboard), and photo organizing and editing (Google Photos). The company leads the development of the Android mobile operating system, the Google Chrome web browser, and Chrome OS (a lightweight, proprietary operating system based on the free and open-source Chromium OS operating system). Google has moved increasingly into hardware; from 2010 to 2015, it partnered with major electronics manufacturers in the production of its Google Nexus devices, and it released multiple hardware products in 2016, including the Google Pixel line of smartphones, Google Home smart speaker, Google Wifi mesh wireless router. Google has also experimented with becoming an Internet carrier (Google Fiber and Google Fi).

Google.com is the most visited website worldwide. Several other Google-owned websites also are on the list of most popular websites, including YouTube and Blogger.[13] On the list of most valuable brands, Google is ranked second by Forbes[14] and fourth by Interbrand.[15] It has received significant criticism involving issues such as privacy concerns, tax avoidance, censorship, search neutrality, antitrust and abuse of its monopoly position.""")

f.close()

f = open("google.txt" , "r+")

f.read()

f.seek(0)

f.readline()

f.readline()

f.readline()

f.readline()

f.readline()

f.readline()

f.readline()

f.readline()

f.readline()

f.close()

f = open("google.txt" , "r+")
for line in f :
    print(line , end = " ")

f.write("fsadasfsa dsaf asf saf")

f.close()

f = open("google.txt"  , "r+")

f.seek(5)

f.write("this is my file write op at 5th locatoin ")

f.close()

f = open("google.txt" , "r+")

len(f.readlines())

l = f.readlines()

l

l1  = []
for i in l[0].split():
    l1.append(i[0])

l1

r	Only for reading. The pointer is located at the start of file and it’s a default mode.
rb	Only for reading in a binary format. The pointer is located at the start of file and it’s a default mode.
r+	To opens a file for the both writing and reading. The pointer is located at the start of file.
rb+	For the both writing and reading operation in binary format. The pointer is located at the start of file.
w	Only for writing. Check for existing file, if its present overwrites in the exists file. If there is no any existing file then, makes a novel file for the writing.
wb	Only for writing in a binary format. Check for existing file, if its present overwrites in the exists file. If there is no any existing file then, makes a novel file for the writing.
w+	For the both writing and reading operation. Check for existing file, if its present overwrites in the exists file. If there is no any existing file then, makes a novel file for the writing and reading.
wb+	For the both writing and reading operation in binary format. Check for existing file, if its present overwrites in the exists file. If there is no any existing file then, makes a novel file for the writing and reading.
a	opens the file for appending; any data written to the file is automatically added to the end. Check for existing file, if its present pointer is set at last of existing file for appending operation. If there is no any existing file then, makes a novel file for the writing.